#!/bin/bash

SAVEDUSER = echo -n mike | sha256sum
SAVEDPASS = echo -n ace | sha256sum

read -p "Enter your username: " USER
read -p "Enter your password: " PASS

# Test if USER matches stored value
if [ "$USER" == "$SAVEDUSER" ] && [ "$PASS" == "$SAVEDPASS" ]
then
    printf “Login Successful\n”
else
    printf “Login Failed\n”
fi
